export const HOME_VIDEOS_SUCCESS = 'HOME_VIDEO_SUCCESS'
export const HOME_VIDEOS_FAIL = 'HOME_VIDEO_FAIL'
export const HOME_VIDEOS_REQUEST = 'HOME_VIDEO_REQUEST'

export const SELECTED_VIDEO_REQUEST = 'SELECTED_VIDEO_REQUEST'
export const SELECTED_VIDEO_SUCCESS = 'SELECTED_VIDEO_SUCCESS'
export const SELECTED_VIDEO_FAIL = 'SELECTED_VIDEO_FAIL'

export const RELATED_VIDEOS_REQUEST = 'RELATED_VIDEOS_REQUEST'
export const RELATED_VIDEOS_SUCCESS = 'RELATED_VIDEOS_SUCCESS'
export const RELATED_VIDEOS_FAIL = 'RELATED_VIDEOS_FAIL'

export const SEARCH_VIDEOS_REQUEST = 'SEARCH_VIDEOS_REQUEST'
export const SEARCH_VIDEOS_SUCCESS = 'SEARCH_VIDEOS_SUCCESS'
export const SEARCH_VIDEOS_FAIL = 'SEARCH_VIDEOS_FAIL'

export const SUBSCRIPTIONS_CHANNEL_REQUEST = 'SUBSCRIPTIONS_CHANNEL_REQUEST'
export const SUBSCRIPTIONS_CHANNEL_SUCCESS = 'SUBSCRIPTIONS_CHANNEL_SUCCESS'
export const SUBSCRIPTIONS_CHANNEL_FAIL = 'SUBSCRIPTIONS_CHANNEL_FAIL'
