export const HOME_VIDEOS_SUCCESS = 'HOME_VIDEO_SUCCESS'
export const HOME_VIDEOS_FAIL = 'HOME_VIDEO_FAIL'
export const HOME_VIDEOS_REQUEST = 'HOME_VIDEO_REQUEST'

export const SUBSCRIPTIONS_CHANNEL_REQUEST = 'SUBSCRIPTIONS_CHANNEL_REQUEST'
export const SUBSCRIPTIONS_CHANNEL_SUCCESS = 'SUBSCRIPTIONS_CHANNEL_SUCCESS'
export const SUBSCRIPTIONS_CHANNEL_FAIL = 'SUBSCRIPTIONS_CHANNEL_FAIL'
