name: Firebase Deployment

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Build & Deployment
        runs-on: ubuntu-latest

        steps:
            - name: get the source code
              uses: actions/checkout@v3

            - name: install node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: install node packages
              run: npm i

            - name: Build
              run: npm run build
              env:
                  CI: false
                  REACT_APP_YOUTUBE_API_KEY: ${{secrets.REACT_APP_YOUTUBE_API_KEY}}
                  REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
                  REACT_APP_PROJECT_ID: ${{secrets.REACT_APP_PROJECT_ID}}
                  REACT_APP_STORAGE_BUCKET: ${{secrets.REACT_APP_STORAGE_BUCKET}}
                  REACT_APP_MES_SENDER_ID: ${{secrets.REACT_APP_MES_SENDER_ID}}
                  REACT_APP_APP_ID: ${{secrets.REACT_APP_APP_ID}}

            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
